version: '3.9'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      - DOZZLE_HOSTNAME=palpi
      - DOZZLE_ENABLE_ACTIONS=true

  palworld-server:
    container_name: palworld-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    env_file:
      - ./palworld.env
    volumes:
      - ./game:/palworld