version: '3.9'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      - DOZZLE_HOSTNAME=palpi
      - DOZZLE_ENABLE_ACTIONS=true

  palworld-server:
    container_name: palworld-server
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=6
      - SERVER_PASSWORD="mordhau"
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ=Europe/Paris
      - ADMIN_PASSWORD="adminPasswordHere"
      - COMMUNITY=false
      - SERVER_NAME="World of Pals"
    volumes:
      - ./game:/palworld/